### ISSUE TITLE
Pinned message,

### ISSUE THREAD

**Issue by geinyuhs** [JoynChat/.github#13]
Pinned option shows in context menu, pinned messages box shows in chat settings

Design: https://www.figma.com/file/JxjAb19IZBjYmTG5YdgotP/WIP?type=design&node-id=612%3A2100&mode=design&t=0EbG0d7oT8Rt9ZJc-1

**Comment by geinyuhs** [comment]
@rishabnayak ready for your review

**Comment by rishabnayak** [comment]
lgtm
