### ISSUE TITLE
Suggestions connections if people are in a group chat together

### ISSUE THREAD

**Issue by geinyuhs** [JoynChat/.github#16]
Design: https://www.figma.com/file/JxjAb19IZBjYmTG5YdgotP/WIP?type=design&node-id=645%3A2517&mode=design&t=0EbG0d7oT8Rt9ZJc-1

**Comment by geinyuhs** [comment]
@rishabnayak ready for review

**Comment by rishabnayak** [comment]
this looks great, lgtm
