### ISSUE TITLE
Connecting Beehiv & SendGrid / Apollo

### ISSUE THREAD

**Issue by geinyuhs** [JoynChat/.github#4]
We are using sendgrid / Apollo to send cold emails & beehiv to manage our newsletter campaign. 

I would like to set it up where if we sent a cold email to someone & they don't unsub then we add them to our beehiv.

**Comment by geinyuhs** [comment]
@rishabnayak lets talk about this tomorrow

**Comment by rishabnayak** [comment]
sendgrid and beehiiv have api's that'll let us do this, how does apollo fit into the pipeline? @austin-yoshino

**Comment by geinyuhs** [comment]
Apollo is where we find the leads. Apollo x Sendgrid sends out the first cold email.


Then Beehive is for our newsletter (consistent email updates). The problem with beehiv is that they only allow up to 10k lifetime manual contact imports.


So heres the sequence I want:

1) We send a cold email using Apollo x Sendgrid
2) If they don't unsub, then we add them to our beehiv newsletter

**Comment by rishabnayak** [comment]
thoughts on this workflow - we send emails using apollo x sendgrid, for every successfully delivered email, we add them to beehiiv, if they unsub, we remove from beehiiv as well

**Comment by geinyuhs** [comment]
I like that - can we sync the unsubs or would we have to do it manually?

**Comment by geinyuhs** [comment]
API for Beehiiv:

![Image](https://github.com/JoynChat/.github/assets/116787153/9b4d0ba9-1fea-4d60-8285-493ad440b29a)

**Comment by geinyuhs** [comment]
Apollo.io credentials

joyn@joynchat.com
Joyn@pp123

**Comment by rishabnayak** [comment]
can you send me beehiiv creds?

**Comment by rishabnayak** [comment]
also we should be able to sync unsubs, need to look into it a bit more but should be possible

**Comment by geinyuhs** [comment]
Beehiiiv

austin@joynchat.com
Joyn@pp123

**Comment by geinyuhs** [comment]
Whenever Apollo sends email, once it's successful Sendgrid returns webhook. then we listen then we add person to beehiiv.

If unsub we use webhook and then unsub. 


Beehiiv has an API for subscribers.

**Comment by rishabnayak** [comment]
im going to assume any email sent to an individual via sendgrid is worthy of adding to the beehiiv newsletter

**Comment by geinyuhs** [comment]
@rishabnayak yup

**Comment by geinyuhs** [comment]
Will work for just new ones. I can send follow-up emails for new people.
